# Generated by Django 3.2.6 on 2021-09-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eng', models.CharField(max_length=200)),
                ('kor', models.CharField(max_length=200)),
                ('desc', models.TextField()),
            ],
        ),
    ]
