# Generated by Django 3.2.7 on 2021-09-14 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('eng', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('eng', models.CharField(max_length=200)),
                ('kor', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.IntegerField()),
                ('imgurl', models.CharField(max_length=255)),
                ('good_cnt', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('eng', models.CharField(max_length=10)),
                ('kor', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PerfumeNote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('note_type', models.IntegerField()),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.note')),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.perfume')),
            ],
        ),
        migrations.CreateModel(
            name='PerfumeCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.perfume')),
            ],
        ),
        migrations.CreateModel(
            name='CategorySeason',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.season')),
            ],
        ),
    ]
