# Generated by Django 3.2.6 on 2021-09-13 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eng', models.CharField(max_length=200)),
                ('kor', models.CharField(max_length=200)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.IntegerField(max_length=1)),
                ('imgurl', models.CharField(max_length=255)),
                ('good_cnt', models.IntegerField()),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eng', models.CharField(max_length=10)),
                ('kor', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('gender', models.IntegerField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserPerfumeList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('perfume_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.perfume')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='PerfumeNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note_type', models.IntegerField()),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.note')),
                ('perfume_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.perfume')),
            ],
        ),
        migrations.CreateModel(
            name='PerfumeCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('perfume_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.perfume')),
            ],
        ),
        migrations.CreateModel(
            name='CategorySeason',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('season_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.season')),
            ],
        ),
    ]
