# Generated by Django 3.2.6 on 2021-09-13 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_brand_categoryseason_note_perfume_perfumecategory_perfumenote_season_user_userperfumelist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryseason',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='categoryseason',
            old_name='season_id',
            new_name='season',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='perfume',
            old_name='brand_id',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='perfumecategory',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='perfumecategory',
            old_name='perfume_id',
            new_name='perfume',
        ),
        migrations.RenameField(
            model_name='perfumenote',
            old_name='note_id',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='perfumenote',
            old_name='perfume_id',
            new_name='perfume',
        ),
        migrations.RenameField(
            model_name='userperfumelist',
            old_name='perfume_id',
            new_name='perfume',
        ),
        migrations.RenameField(
            model_name='userperfumelist',
            old_name='user_id',
            new_name='user',
        ),
    ]
