# Generated by Django 3.2.6 on 2021-09-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210913_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='gender',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(),
        ),
    ]
