# Generated by Django 3.2.7 on 2021-09-17 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserPerfumeList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.perfume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
